### ISSUE TITLE
Chrome OS ?

### ISSUE THREAD

**Issue by Lildishsoap1710** [l0u1sg/GeForce-Now-Portable#1]
I there anyway to do this on chrome os or am I not getting the steps.

**Comment by l0u1sg** [comment]
Hi, 
From memory, GeForce Now has a domain for chromebooks. So you can access it directly from your web browser :)

**Comment by Lildishsoap1710** [comment]
ok I will try later and get back to you.

**Comment by l0u1sg** [comment]
Yes, thanks !
