### ISSUE TITLE
stuck on loading wheel

### ISSUE THREAD

**Issue by ILBB7468** [l0u1sg/GeForce-Now-Portable#4]
I extracted the folder ran the app, and it got stuck on the green loading wheel, I checked my appdata local folder and the nvidia corporation folder is there with its stuff in it, but when I open the app, its still just the loading wheel, please help.

**Comment by l0u1sg** [comment]
Hello!

Unfortunately, the basics of the GeForce Now application has changed. I don't have much time to deal with it anymore. I will archive the repo.

Unfortunately I don't have a solution for you...
